### PR TITLE
feat: add tags for elements on auction

### PR DESCRIPTION
**Pull request by andredevjs**
We are going to merge on sale and auction sections into one. Tag is so that we are able to identify the ones that are on auction.

Screenshot 2023-07-31 at 20 29 36

### CODE REVIEW

**Review by habibitcoin — COMMENTED** [review]
Will this only show the auction is live? I'd assume it would show for upcoming auctions as well, just based how the logic is written

but when I view https://deploy-preview-290.test.deezy.place/inscription/f58907bbbfe34d89c7cf2ad4fd9053eb1e3a6a000bdf5e0c1b085801dbd6d2bfi0 inside my wallet, I do not see the tag

**Comment by habibitcoin** [comment]
Yeah still not seeing any difference

**Comment by andredevjs** [comment]
@habibitcoin this only affects the ordinal cards. I created an auction and apply a small fix pls try again.

**Review by habibitcoin — APPROVED** [review]
Got it, awesome!

**Pull request merged**
