### PR TITLE
feat: Create a view to see other competing bids

### PR DESCRIPTION
**Pull request by topether21**
Please create a Bid and you will see your bid.

https://linear.app/deezy/issue/ENG-137/create-a-view-to-see-other-competing-bids

image
image
image

### CODE REVIEW

**Review by habibitcoin — CHANGES_REQUESTED** [review]
Looks good! Only request is can we also have this shown in the unauthenticated view? The same way we also show if an item is listed, even if the wallet is not connected/authenticated

Will give us more ability to generate excitement before even connecting the wallet

**Comment by topether21** [comment]
@habibitcoin good catch.

image

**Comment by topether21** [comment]
@habibitcoin @dannydeezy 
image

**Review by habibitcoin — APPROVED** [review]
Excellent!

**Pull request merged**
