### PR TITLE
chore: call populate psbt on click buy

### PR DESCRIPTION
**Pull request by topether21**
@andredevjs If we call populate after click on buy fee calculation doesn’t have previous value.

### CODE REVIEW

**Review by andredevjs — CHANGES_REQUESTED** [review]
Please do not merge yet

**Comment by andredevjs** [comment]
@topether21 please read comment on linear about this.

**Comment by dannydeezy** [comment]
@topether21 whats the status here? can we merge?

**Comment by topether21** [comment]
Implemented here: https://github.com/deezy-inc/deezy-place/pull/300

**Pull request closed without merging**
